name: Flask App CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        echo "No tests configured yet"
        # Example: python -m unittest discover tests

    - name: Build Docker Image
      run: docker build -t flask-app .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag Docker Image
      run: |
        docker tag flask-app:latest your-dockerhub-username/flask-app:latest
        # Replace 'your-dockerhub-username' with your actual Docker Hub username

    - name: Push Docker Image to Docker Hub
      run: |
        docker push your-dockerhub-username/flask-app:latest
